steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'set -euo pipefail; if [ -z "${MAPBOX_ACCESS_TOKEN:-}" ]; then echo "ERROR: MAPBOX_ACCESS_TOKEN is empty in build step" 1>&2; exit 1; else echo "Verified: MAPBOX_ACCESS_TOKEN is present in build step"; fi; docker build -t gcr.io/$PROJECT_ID/biocirv-frontend:$SHORT_SHA --build-arg=MAPBOX_ACCESS_TOKEN_BUILD="${MAPBOX_ACCESS_TOKEN}" .'
    secretEnv: ['MAPBOX_ACCESS_TOKEN']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/biocirv-frontend:$SHORT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'biocirv-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/biocirv-frontend:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/biocirv-frontend:$SHORT_SHA'

availableSecrets:
  secretManager:
    - versionName: 'projects/$PROJECT_ID/secrets/mapbox-access-token/versions/latest'
      env: 'MAPBOX_ACCESS_TOKEN'
